# Logistic Regression

### Predicting the status of a food desert based on distance from grocery store to bus stop, along with other demographic variables

#### Selected Variables:


LILATracts_halfAnd10: Flag for food desert when considering low accessibilty at 1/2 and 10 miles


distance: avg location from a SNAP store to a bus stop

POP2010: Population, tract total

OHU2010: Housing units, total

PovertyRate: Tract Poverty Rate

MedianFamilyIncome: Tract Median Family Income*

TractLOWI: Tract low-income population, number

TractKids: Tract children age 0-17, number

TractSeniors: Tract seniors age 65+, number

TractWhite: Tract White population, number

TractBlack: Track Black or African American population, number

TractAsian: Tract Asian population, number

TractNHOPI: Tract Native Hawaiian and Other Pacific Islander population, number

TractAIAN: Tract American Indian and Alaska Native population, number

TractOMultir: Tract Other/Multiple race population, number

TractHispanic: Tract Hispanic or Latino population, number

TractHUNV: Tract housing unites without a vehicle, number

TractSNAP: Tract housing units reveiving SNAP benefits, number







# Code

In [284]:
#dependencies
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_excel(open('DataDownload2015.xlsx', 'rb'), sheet_name = 'Food Access Research Atlas', converters={'CensusTract':str})


In [ ]:
data.head()

In [104]:
filtered_data = data[data['County'] == 'Maricopa']

In [105]:
filtered_data.head()

CensusTract    State    County  Urban  POP2010  OHU2010  \
1459  04013010101  Arizona  Maricopa      0     5073     2246   
1460  04013010102  Arizona  Maricopa      1     4640     2041   
1461  04013030401  Arizona  Maricopa      1     4283     2008   
1462  04013030402  Arizona  Maricopa      1     3895     1706   
1463  04013040502  Arizona  Maricopa      1     4861     2188   

      GroupQuartersFlag  NUMGQTRS  PCTGQTRS  LILATracts_1And10  ...  \
1459                  0         0  0.000000                  0  ...   
1460                  0         0  0.000000                  0  ...   
1461                  0        47  0.010974                  0  ...   
1462                  0         0  0.000000                  0  ...   
1463                  0       169  0.034766                  1  ...   

      TractSeniors  TractWhite  TractBlack  TractAsian  TractNHOPI  TractAIAN  \
1459          1645        4869          44          61           7         12   
1460          1240        4367          21         108           5          6   
1461          1431        4100          30          65           0         11   
1462           792        3627          27          27           3         18   
1463          1340        4343          12          24           1         85   

      TractOMultir  TractHispanic  TractHUNV  TractSNAP  
1459            80            161         42          0  
1460           133            169         73         14  
1461            77            111         58         21  
1462           193            320          0         19  
1463           396            759        195        258  

[5 rows x 147 columns]

In [106]:
for col in filtered_data.columns:
    print (col)

CensusTract
State
County
Urban
POP2010
OHU2010
GroupQuartersFlag
NUMGQTRS
PCTGQTRS
LILATracts_1And10
LILATracts_halfAnd10
LILATracts_1And20
LILATracts_Vehicle
HUNVFlag
LowIncomeTracts
PovertyRate
MedianFamilyIncome
LA1and10
LAhalfand10
LA1and20
LATracts_half
LATracts1
LATracts10
LATracts20
LATractsVehicle_20
LAPOP1_10
LAPOP05_10
LAPOP1_20
LALOWI1_10
LALOWI05_10
LALOWI1_20
lapophalf
lapophalfshare
lalowihalf
lalowihalfshare
lakidshalf
lakidshalfshare
laseniorshalf
laseniorshalfshare
lawhitehalf
lawhitehalfshare
lablackhalf
lablackhalfshare
laasianhalf
laasianhalfshare
lanhopihalf
lanhopihalfshare
laaianhalf
laaianhalfshare
laomultirhalf
laomultirhalfshare
lahisphalf
lahisphalfshare
lahunvhalf
lahunvhalfshare
lasnaphalf
lasnaphalfshare
lapop1
lapop1share
lalowi1
lalowi1share
lakids1
lakids1share
laseniors1
laseniors1share
lawhite1
lawhite1share
lablack1
lablack1share
laasian1
laasian1share
lanhopi1
lanhopi1share
laaian1
laaian1share
laomultir1
laomultir1share
lahisp1
lahisp1share
lahunv1

In [107]:
selected_columns = ['CensusTract', 'State', 'County', 'POP2010', 'OHU2010',
                   'NUMGQTRS', 'LILATracts_halfAnd10', 'PovertyRate', 
                   'MedianFamilyIncome', 'TractLOWI', 'TractKids',
                   'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian',
                   'TractNHOPI', 'TractAIAN', 'TractOMultir', 'TractHispanic',
                   'TractHUNV', 'TractSNAP']

In [108]:
filtered_data = filtered_data[selected_columns]

filtered_data.head()

CensusTract    State    County  POP2010  OHU2010  NUMGQTRS  \
1459  04013010101  Arizona  Maricopa     5073     2246         0   
1460  04013010102  Arizona  Maricopa     4640     2041         0   
1461  04013030401  Arizona  Maricopa     4283     2008        47   
1462  04013030402  Arizona  Maricopa     3895     1706         0   
1463  04013040502  Arizona  Maricopa     4861     2188       169   

      LILATracts_halfAnd10  PovertyRate  MedianFamilyIncome  TractLOWI  ...  \
1459                     0          4.5              116833        429  ...   
1460                     0          7.9              143490        598  ...   
1461                     0          6.2              107693        628  ...   
1462                     0          7.6              108188        599  ...   
1463                     1         20.7               50377       2513  ...   

      TractSeniors  TractWhite  TractBlack  TractAsian  TractNHOPI  TractAIAN  \
1459          1645        4869          44          61           7         12   
1460          1240        4367          21         108           5          6   
1461          1431        4100          30          65           0         11   
1462           792        3627          27          27           3         18   
1463          1340        4343          12          24           1         85   

      TractOMultir  TractHispanic  TractHUNV  TractSNAP  
1459            80            161         42          0  
1460           133            169         73         14  
1461            77            111         58         21  
1462           193            320          0         19  
1463           396            759        195        258  

[5 rows x 21 columns]

In [109]:
avg_distances = pd.read_csv('avg_distances.csv', dtype={'Census Tract':str})

In [110]:
avg_distances.head()

len(avg_distances)

916

In [117]:
#len(avg_distances[(avg_distances['distance'] == 99) | (avg_distances['distance'] == 88)])

In [118]:
#filtered_distances = avg_distances[(avg_distances['distance'] != 99) & (avg_distances['distance'] != 88)]

In [119]:
#combined_df = filtered_data.merge(filtered_distances, left_on='CensusTract', right_on='Census Tract')
combined_df = filtered_data.merge(avg_distances, left_on='CensusTract', right_on='Census Tract')

In [120]:
combined_df.head()

CensusTract    State    County  POP2010  OHU2010  NUMGQTRS  \
0  04013010101  Arizona  Maricopa     5073     2246         0   
1  04013010102  Arizona  Maricopa     4640     2041         0   
2  04013030401  Arizona  Maricopa     4283     2008        47   
3  04013030402  Arizona  Maricopa     3895     1706         0   
4  04013040502  Arizona  Maricopa     4861     2188       169   

   LILATracts_halfAnd10  PovertyRate  MedianFamilyIncome  TractLOWI  ...  \
0                     0          4.5              116833        429  ...   
1                     0          7.9              143490        598  ...   
2                     0          6.2              107693        628  ...   
3                     0          7.6              108188        599  ...   
4                     1         20.7               50377       2513  ...   

   TractBlack  TractAsian  TractNHOPI  TractAIAN  TractOMultir  TractHispanic  \
0          44          61           7         12            80            161   
1          21         108           5          6           133            169   
2          30          65           0         11            77            111   
3          27          27           3         18           193            320   
4          12          24           1         85           396            759   

   TractHUNV  TractSNAP  Census Tract  distance  
0         42          0   04013010101  4.124293  
1         73         14   04013010102  4.124293  
2         58         21   04013030401  4.124293  
3          0         19   04013030402  4.124293  
4        195        258   04013040502  4.124293  

[5 rows x 23 columns]

In [121]:
combined_df.to_csv('combined_data.csv')

## Model

In [262]:
predictors1 = ['POP2010', 'OHU2010','NUMGQTRS', 'PovertyRate',
              'MedianFamilyIncome', 'TractLOWI', 'TractKids',
              'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian',
              'TractNHOPI', 'TractAIAN', 'TractOMultir', 'TractHispanic',
              'TractHUNV', 'TractSNAP']
predictors2 = ['POP2010', 'OHU2010','NUMGQTRS', 'PovertyRate',
              'MedianFamilyIncome', 'TractLOWI', 'TractKids',
              'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian',
              'TractNHOPI', 'TractAIAN', 'TractOMultir', 'TractHispanic',
              'TractHUNV', 'TractSNAP', 'distance']

predictors3 = ['POP2010','OHU2010', 'PovertyRate',
              'MedianFamilyIncome']

predictors4 = ['POP2010','OHU2010', 'PovertyRate',
              'MedianFamilyIncome', 'distance']

predictors5 = ['distance']

predictors6 = ['PovertyRate', 'TractNHOPI']

predictors7 = ['PovertyRate', 'distance', 'TractHUNV']

predictors8 = ['PovertyRate']

#X = combined_df['distance'].values.reshape(-1,1)
X = combined_df[predictors2]
y = combined_df['LILATracts_halfAnd10']

In [275]:
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X)
X = X_scaler.transform(X)

In [276]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [277]:
logistic_regression= LogisticRegression(max_iter=10000)
logistic_regression.fit(X_train,y_train)
y_pred=logistic_regression.predict(X_test)

In [278]:
confusion_matrix = pd.crosstab(y_test, y_pred, rownames=['Actual'], colnames=['Predicted'])
#sn.heatmap(confusion_matrix, annot=True)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)


array([[140,   6],
       [ 25,  58]], dtype=int64)

In [279]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [280]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
plt.show()

Accuracy:  0.8646288209606987


In [281]:
logistic_regression.coef_

array([[-0.46046889, -0.23696811,  0.9142217 ,  3.6319226 , -3.51378167,
         2.92543509, -1.38801609,  1.04979897, -0.88866692,  0.35067512,
        -1.18486323,  0.68736174, -0.38728782,  1.21991777,  1.19626572,
         0.15469817,  1.72649144,  0.09525665]])

In [282]:
coef_dict = dict(zip(predictors2 , logistic_regression.coef_[0]))

In [283]:
coef_dict

{'POP2010': -0.4604688860382479,
 'OHU2010': -0.23696811347178423,
 'NUMGQTRS': 0.9142216984561602,
 'PovertyRate': 3.6319225993774,
 'MedianFamilyIncome': -3.5137816670323625,
 'TractLOWI': 2.925435093975956,
 'TractKids': -1.3880160882591053,
 'TractSeniors': 1.0497989656194118,
 'TractWhite': -0.8886669168402189,
 'TractBlack': 0.35067511971009674,
 'TractAsian': -1.1848632286513527,
 'TractNHOPI': 0.687361743497711,
 'TractAIAN': -0.38728781876031043,
 'TractOMultir': 1.219917770205012,
 'TractHispanic': 1.1962657152488194,
 'TractHUNV': 0.15469817079583628,
 'TractSNAP': 1.726491442324211,
 'distance': 0.09525665254846856}